version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: app_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d app_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      postgres:
        condition: service_healthy
      leetcode:
        condition: service_healthy
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/app_db
      SPRING_DATASOURCE_USERNAME: app_user
      SPRING_DATASOURCE_PASSWORD: secretpass
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      BOT_TOKEN: ${BOT_TOKEN}
      GPT_TOKEN: ${GPT_TOKEN}
    ports:
      - "8080:8080"
    restart: unless-stopped

  leetcode:
    image: alfaarghya/alfa-leetcode-api:2.0.1
    container_name: leetcode
    ports:
      - "3000:3000"

volumes:
  postgres_data: